---
- hosts: all
  tasks:
    - file: src={{ curdir }}/files/{{ item }} dest=~/.{{ item }} state=link force=yes
      with_items:
        - gitconfig
        - spacemacs
        - git-prompt.sh
        - bash_customize

    - lineinfile:
        dest="~/.bashrc" line="source ~/.bash_customize" state=present create=yes
